### ISSUE TITLE
REST framework: resource bindings

### ISSUE THREAD

**Issue by felix-b** [felix-b/NWheels#11]

**Comment by felix-b** [comment]
![image](https://cloud.githubusercontent.com/assets/5800163/23696432/429b8fdc-03ec-11e7-99ab-98928c3f6783.png)

**Comment by ILyaIL83** [comment]
PATCH is not a part of HTTP 1.1
https://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html
https://www.w3schools.com/tags/ref_httpmethods.asp
but it was in draft https://www.w3.org/Protocols/HTTP/1.1/draft-ietf-http-v11-spec-01#PATCH

**Comment by felix-b** [comment]
If it was moved to DONE, I guess it has to be closed.
