### ISSUE TITLE
Communication platform: HTTP endpoint

### ISSUE THREAD

**Issue by felix-b** [felix-b/NWheels#13]

**Comment by felix-b** [comment]
@ILyaIL83, can we close this one, as we already merged PR #22?

**Comment by felix-b** [comment]
On the second thought, we have two flaws in our initial implementation of HTTP/REST stack:

- Everything should be async, starting from Kestrel request handler, and including our IRestResourceHandler abstraction. For instance, operations on requested REST resources can be heavy, and we don't want to block threads on server.
- Kestrel-based implementation should be moved into a separate adapter assembly NWheels.Platform.Messaging.Adapters.Kestrel -- see #29.

**Comment by felix-b** [comment]
Ilya, can we close this one? It looks like you implemented what we wanted in the first milestone.

**Comment by ILyaIL83** [comment]
For now it can be closed, but work to do is:
- implement async methodology(to prevent thread locking)
- add static assets handler(now we have only rest handler)

**Comment by felix-b** [comment]
OK, further work will be tracked here:
- Issue #43 (implement async methodology(to prevent thread locking)
- PR #34 will add ability to have arbitrary handlers behind an endpoint
Both are included in PR #34.
