### ISSUE TITLE
First Happy Path sample application

### ISSUE THREAD

**Issue by felix-b** [felix-b/NWheels#18]

**Comment by ILyaIL83** [comment]
Just add description from https://github.com/felix-b/NWheels/milestone/2:
Create a minimal single-module application, which consists of 1 microservice, 1 transaction script, and 1 web page. The web page should ask user her name, invoke transaction script through backend API (REST/HTTP), and display the output. The output should be something like "Hello, [name]!".

**Comment by felix-b** [comment]
Done
