### ISSUE TITLE
xcopy cannot be used in post-build event

### ISSUE THREAD

**Issue by felix-b** [felix-b/NWheels#32]
There is no xcopy on Linux....

![xcopy-linux](https://cloud.githubusercontent.com/assets/5800163/24227344/20e4e19c-0f75-11e7-93d1-4df9f17d70cf.png)

**Comment by ILyaIL83** [comment]
As was discussed, we are going to use CLI for different goals such as packaging here.

**Comment by felix-b** [comment]
No action on this issue is required. Once CLI is implemented (#35), this one will be closed as irrelevant.

**Comment by felix-b** [comment]
Not relevant as PR #33 deletes the project NWheels.Host whatsoever.
