### ISSUE TITLE
Command-line interface (CLI)

### ISSUE THREAD

**Issue by felix-b** [felix-b/NWheels#35]
Create command line interface that will allow invocation of a pluggable set of commands. 

The implementation logic of commands can be either coupled or decoupled from the CLI (this is a question; as for Unix philosophy, the CLI is the master). 

Currently, we need two commands:
```
nwheels service --build path/to/microservice.xml
nwheels service --run path/to/microservice.xml path/to/environment.xml
```
or combination of both:
```
nwheels service --build --run path/to/microservice.xml path/to/environment.xml
```

**Comment by felix-b** [comment]
First step is to choose command-line library. My suggestion is [System.CommandLine from corefxlab](https://github.com/dotnet/corefxlab/blob/master/src/System.CommandLine/README.md).

Any feedback is welcome...

**Comment by ILyaIL83** [comment]
Is there a sense to send full files paths as arguments? Nowadays their short names are hard coded and documented. So why not to send directory path?

**Comment by felix-b** [comment]
Basically I agree. For sure, ```nwheels service --run``` should expect both files to be in the microservice directory created by ```nwheels service --build```.

Regarding ```nwheels service --build```, it makes sense to expect ```microservice.xml``` to be in the source directory (OK; so we need at least two more parameters, the source path and the destination path). But what if ```environment.xml``` comes from somewhere else? 

Current structure of ```environment.xml``` allows specifying parameters of exactly one environment. So it makes sense that the ```environment.xml``` in the sources will specify environment for local dev boxes. During deployment procedure to test/prod environments, the contents of ```environment.xml``` will most likely come from somewhere else.

Here is how it may look.

#### To run a microservice from an existing working directory:
 
```nwheels service --run [--work /path/to/service/folder]```

Where ```--work``` specifies path to microservice working folder built with ```nwheels service --build```. If not specified, current directory will be assumed.

#### To build microservice working directory from sources:

```nwheels service --build --src /path/to/source/folder [--work /path/to/working/folder] [--env /path/to/environment.xml]```

Where:
- ```--src``` specifies path to sources of microservice project. The ```microservice.xml``` is expected to be there.
- ```--work``` specifies output path, which is the working directory from where microservice can be run. If not specified, current directory is assumed.
- ```--env``` specifies path to ```environment.xml``` file to use (arbitrary file name can be used). The file will be copied to the working directory under the name ```environment.xml```. If not specified, the ```environment.xml``` file located in the source directory will be used.

#### Combination of build and run

The combination is required for F5 debugging in Visual Studio, because only one external program can be specified in project Debug settings.

```nwheels service --build --run --src /path/to/source/folder [--work /path/to/working/folder] [--env /path/to/environment.xml]```

with all the same parameters specified above.

**Comment by felix-b** [comment]
One doubt: I'm sure want to test the CLI, but should I do unit testing, or system testing? 

Meanwhile I prepared some infra for unit testing the CLI, but I'm not sure it is the best approach...

**Comment by felix-b** [comment]
I came to conclusion that unit testing the CLI doesn't worth effort and complexity it adds. In the last commit to #37, I got rid of unit test project and ```ICommandContext``` abstraction. The code got simple again. We will have to system-test it in the future.

**Comment by felix-b** [comment]
A problem. While the CLI is going to be an awesome tool for deployment... it doesn't resolve our current issue #32 for F5 debugging in Visual Studio:

In my implementation of ```nwheels publish```, I use ```dotnet publish``` on projects that correspond to modules in ```microservice.xml```. This is to avoid implementing a kind of ```dotnet-publish``` by myself.

Now, ```dotnet-publish``` has two problems with the F5 scenario:
- it is slow; it takes about 20 seconds to publish a microservice of 4 modules; this is quite annoying if I do F5 frequently.
- it encounters "cannot access file... in use by another process..." errors when the solution is open in Visual Studio; so it cannot be used for F5 debugging.

It looks like the best approach for F5 debugging is load modules from where they were compiled. I know we had problems there, so we opted to bring all binaries together by copying. Maybe we should attack that issue again.

**Comment by ILyaIL83** [comment]
So, how many modes/scenarios/ways do we have/plan for now(release/debug directories and packages)?

**Comment by ILyaIL83** [comment]
Why not to add to "run" command new argument which will tell what to do before publish or copy - this way we can use copy for developing and publish for integration tests and deployment?

**Comment by felix-b** [comment]
My current vision is as follows:

- For F5 debugging in Visual Studio, I'm currently investigating handling the ```AssemblyLoadContext.Resolving``` event. Meanwhile is looks promising. In this way, we won't have to copy anything when working in Visual Studio.
- For microservice deployment and system tests, we will use the CLI ```nwheels publish``` and ```nwheels run```. Note that the CLI itself will also be published to the microservice folder. When we want to run a micriservice, we will execute ```nwheels run``` from the microservice folder (though ```nwheels run``` is also able to run from a different location).
- Currently, ```nwheels run``` can automatically perform ```nwheels publish```, but if we handle F5 debugging without the CLI, then it is no longer necessary
- Doing just copy to build "runnable" microservice folder is not enough. The DLLs from NuGet packages and many .NET Framework assemblies don't present in the Bin folder. In order to correctly build a "runnable" microservice folder, we need to use ```dotnet publish```. (Or we can develop our own ```dotnet-publish```, but I don't believe we want to).

**Comment by ILyaIL83** [comment]
OK. So we are good again.

**Comment by felix-b** [comment]
```AssemblyLoadContext.Resolving``` does the trick. I am able to load an assembly from any location. The idea is to have a list of folders, and every time an assembly needs to be loaded, search in these folders.

In deployment, there is only one folder to search -- the publish folder. 

For F5 debugging, I assume certain structure of solution folders. Currently, I assume that all projects reside in folders named after their assemblies, in immediate subfolders of the solution folder.  This has to be extensible, so that a concrete application will be able to plug in its own structure.

**Comment by felix-b** [comment]
The last problem with F5 debugging is locating assemblies from NuGet packages. I can just go to ```%UserProfile%\.NuGet\Packages\```_package_name_```\```_package_version_```\lib\```_package_platform_. 
But it's not that simple. In the Resolving handler, I have details of assembly, not its package:
- assembly name doesn't always equal to package name
- assembly version doesn't always equal to package version; sometimes version redirects need to be taken into account.
- package platform is not always "netstandard1.6"; there needs to be additional logic of platform compatibility.

All these lead me to conclude that I don't want to write that logic. It is already written. I only have to figure out how I can reuse it. Currently looking through https://github.com/NuGet/NuGet.Client, https://github.com/dotnet/cli, and https://github.com/Microsoft/msbuild.

**Comment by felix-b** [comment]
We can also ask our users to do publish at least once, but that's ugly; every time they'll add another package reference, they'll need to do publish again; and then we'll answer their issues, telling them they forgot to do so...

**Comment by felix-b** [comment]
Progress in locating assemblies from NuGet packages. MSBuild has a target for that, named ```ComputeFilesToPublish```. It seems to do the work. 

This target in turn uses a task class named ```ResolvePublishAssemblies``` (here it is: https://github.com/dotnet/sdk/blob/6e8935b1a75240d14948a23c0423198e4bba76a4/src/Tasks/Microsoft.NET.Build.Tasks/ResolvePublishAssemblies.cs). 

If I use necessary MSBuild packages from NuGet, I can run that task in-process from the CLI. Like this: http://codefocus.blogspot.co.il/2008/10/running-msbuild-tasks-programatically.html

**Comment by felix-b** [comment]
Good news: the **ResolvePublishAssemblies** task indeed does what we need. 

Meanwhile I figured out how to run it with MSBuild. With the following project file **p1.proj**:
```xml
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    
    <UsingTask 
        TaskName="ResolvePublishAssemblies" 
        AssemblyFile="C:\Program Files\dotnet\sdk\1.0.0\Sdks\Microsoft.NET.Sdk\build\..\tools\netcoreapp1.0/Microsoft.NET.Build.Tasks.dll" />

    <Target Name="Build">  
        <ResolvePublishAssemblies 
            ProjectPath="C:\Home\NWheels\Source\NWheels.Injection.Adapters.Autofac\NWheels.Injection.Adapters.Autofac.csproj"
            AssetsFilePath="C:\Home\NWheels\Source\NWheels.Injection.Adapters.Autofac\obj\project.assets.json"
            TargetFramework=".NETStandard,Version=v1.6">
            <Output TaskParameter="AssembliesToPublish" ItemName="ResolvedAssembliesToPublish" />
        </ResolvePublishAssemblies>
        <Message Text="%(DestinationSubPath)=@(ResolvedAssembliesToPublish)" Importance="high" />  
    </Target>  
    
</Project>
```
the command:
```
dotnet msbuild p1.proj /nologo
```
produces the following output:
```
  Autofac.dll=C:\Users\felix.b\.nuget\packages\autofac\4.4.0\lib\netstandard1.1\Autofac.dll
  runtimes\debian.8-x64\native\System.Security.Cryptography.Native.OpenSsl.so=C:\Users\felix.b\.nuget\packages\runtime.debian.8-x64.runtime.native.system.security.cryptography.openssl\4.3.0\runtimes\debian.8-x64\native\System.Security.Cryptography.Native.OpenSsl.so
  runtimes\fedora.23-x64\native\System.Security.Cryptography.Native.OpenSsl.so=C:\Users\felix.b\.nuget\packages\runtime.fedora.23-x64.runtime.native.system.security.cryptography.openssl\4.3.0\runtimes\fedora.23-x64\native\System.Security.Cryptography.Native.OpenSsl.so
  runtimes\fedora.24-x64\native\System.Security.Cryptography.Native.OpenSsl.so=C:\Users\felix.b\.nuget\packages\runtime.fedora.24-x64.runtime.native.system.security.cryptography.openssl\4.3.0\runtimes\fedora.24-x64\native\System.Security.Cryptography.Native.OpenSsl.so
  runtimes\opensuse.13.2-x64\native\System.Security.Cryptography.Native.OpenSsl.so=C:\Users\felix.b\.nuget\packages\runtime.opensuse.13.2-x64.runtime.native.system.security.cryptography.openssl\4.3.0\runtimes\opensuse.13.2-x64\native\System.Security.Cryptography.Native.OpenSsl.so
  runtimes\opensuse.42.1-x64\native\System.Security.Cryptography.Native.OpenSsl.so=C:\Users\felix.b\.nuget\packages\runtime.opensuse.42.1-x64.runtime.native.system.security.cryptography.openssl\4.3.0\runtimes\opensuse.42.1-x64\native\System.Security.Cryptography.Native.OpenSsl.so
  runtimes\osx.10.10-x64\native\System.Security.Cryptography.Native.Apple.dylib=C:\Users\felix.b\.nuget\packages\runtime.osx.10.10-x64.runtime.native.system.security.cryptography.apple\4.3.0\runtimes\osx.10.10-x64\native\System.Security.Cryptography.Native.Apple.dylib
  runtimes\osx.10.10-x64\native\System.Security.Cryptography.Native.OpenSsl.dylib=C:\Users\felix.b\.nuget\packages\runtime.osx.10.10-x64.runtime.native.system.security.cryptography.openssl\4.3.0\runtimes\osx.10.10-x64\native\System.Security.Cryptography.Native.OpenSsl.dylib
  runtimes\rhel.7-x64\native\System.Security.Cryptography.Native.OpenSsl.so=C:\Users\felix.b\.nuget\packages\runtime.rhel.7-x64.runtime.native.system.security.cryptography.openssl\4.3.0\runtimes\rhel.7-x64\native\System.Security.Cryptography.Native.OpenSsl.so
  runtimes\ubuntu.14.04-x64\native\System.Security.Cryptography.Native.OpenSsl.so=C:\Users\felix.b\.nuget\packages\runtime.ubuntu.14.04-x64.runtime.native.system.security.cryptography.openssl\4.3.0\runtimes\ubuntu.14.04-x64\native\System.Security.Cryptography.Native.OpenSsl.so
  runtimes\ubuntu.16.04-x64\native\System.Security.Cryptography.Native.OpenSsl.so=C:\Users\felix.b\.nuget\packages\runtime.ubuntu.16.04-x64.runtime.native.system.security.cryptography.openssl\4.3.0\runtimes\ubuntu.16.04-x64\native\System.Security.Cryptography.Native.OpenSsl.so
  runtimes\ubuntu.16.10-x64\native\System.Security.Cryptography.Native.OpenSsl.so=C:\Users\felix.b\.nuget\packages\runtime.ubuntu.16.10-x64.runtime.native.system.security.cryptography.openssl\4.3.0\runtimes\ubuntu.16.10-x64\native\System.Security.Cryptography.Native.OpenSsl.so
  System.AppContext.dll=C:\Users\felix.b\.nuget\packages\system.appcontext\4.3.0\lib\netstandard1.6\System.AppContext.dll
  System.Buffers.dll=C:\Users\felix.b\.nuget\packages\system.buffers\4.3.0\lib\netstandard1.1\System.Buffers.dll
  System.Collections.Concurrent.dll=C:\Users\felix.b\.nuget\packages\system.collections.concurrent\4.3.0\lib\netstandard1.3\System.Collections.Concurrent.dll
  System.Collections.Immutable.dll=C:\Users\felix.b\.nuget\packages\system.collections.immutable\1.3.1\lib\netstandard1.0\System.Collections.Immutable.dll
  System.ComponentModel.dll=C:\Users\felix.b\.nuget\packages\system.componentmodel\4.0.1\lib\netstandard1.3\System.ComponentModel.dll
  System.Diagnostics.DiagnosticSource.dll=C:\Users\felix.b\.nuget\packages\system.diagnostics.diagnosticsource\4.3.0\lib\netstandard1.3\System.Diagnostics.DiagnosticSource.dll
  runtimes\unix\lib\netstandard1.3\System.Globalization.Extensions.dll=C:\Users\felix.b\.nuget\packages\system.globalization.extensions\4.3.0\runtimes\unix\lib\netstandard1.3\System.Globalization.Extensions.dll
  runtimes\win\lib\netstandard1.3\System.Globalization.Extensions.dll=C:\Users\felix.b\.nuget\packages\system.globalization.extensions\4.3.0\runtimes\win\lib\netstandard1.3\System.Globalization.Extensions.dll
  runtimes\unix\lib\netstandard1.3\System.IO.Compression.dll=C:\Users\felix.b\.nuget\packages\system.io.compression\4.3.0\runtimes\unix\lib\netstandard1.3\System.IO.Compression.dll
  runtimes\win\lib\netstandard1.3\System.IO.Compression.dll=C:\Users\felix.b\.nuget\packages\system.io.compression\4.3.0\runtimes\win\lib\netstandard1.3\System.IO.Compression.dll
  System.IO.Compression.ZipFile.dll=C:\Users\felix.b\.nuget\packages\system.io.compression.zipfile\4.3.0\lib\netstandard1.3\System.IO.Compression.ZipFile.dll
  System.IO.FileSystem.Primitives.dll=C:\Users\felix.b\.nuget\packages\system.io.filesystem.primitives\4.3.0\lib\netstandard1.3\System.IO.FileSystem.Primitives.dll
  System.Linq.dll=C:\Users\felix.b\.nuget\packages\system.linq\4.3.0\lib\netstandard1.6\System.Linq.dll
  System.Linq.Expressions.dll=C:\Users\felix.b\.nuget\packages\system.linq.expressions\4.3.0\lib\netstandard1.6\System.Linq.Expressions.dll
  runtimes\unix\lib\netstandard1.6\System.Net.Http.dll=C:\Users\felix.b\.nuget\packages\system.net.http\4.3.0\runtimes\unix\lib\netstandard1.6\System.Net.Http.dll
  runtimes\win\lib\netstandard1.3\System.Net.Http.dll=C:\Users\felix.b\.nuget\packages\system.net.http\4.3.0\runtimes\win\lib\netstandard1.3\System.Net.Http.dll
  System.ObjectModel.dll=C:\Users\felix.b\.nuget\packages\system.objectmodel\4.3.0\lib\netstandard1.3\System.ObjectModel.dll
  System.Reflection.Emit.dll=C:\Users\felix.b\.nuget\packages\system.reflection.emit\4.3.0\lib\netstandard1.3\System.Reflection.Emit.dll
  System.Reflection.Emit.ILGeneration.dll=C:\Users\felix.b\.nuget\packages\system.reflection.emit.ilgeneration\4.3.0\lib\netstandard1.3\System.Reflection.Emit.ILGeneration.dll
  System.Reflection.Emit.Lightweight.dll=C:\Users\felix.b\.nuget\packages\system.reflection.emit.lightweight\4.3.0\lib\netstandard1.3\System.Reflection.Emit.Lightweight.dll
  System.Reflection.TypeExtensions.dll=C:\Users\felix.b\.nuget\packages\system.reflection.typeextensions\4.3.0\lib\netstandard1.5\System.Reflection.TypeExtensions.dll
  System.Runtime.InteropServices.RuntimeInformation.dll=C:\Users\felix.b\.nuget\packages\system.runtime.interopservices.runtimeinformation\4.3.0\lib\netstandard1.1\System.Runtime.InteropServices.RuntimeInformation.dll
  runtimes\unix\lib\netstandard1.1\System.Runtime.InteropServices.RuntimeInformation.dll=C:\Users\felix.b\.nuget\packages\system.runtime.interopservices.runtimeinformation\4.3.0\runtimes\unix\lib\netstandard1.1\System.Runtime.InteropServices.RuntimeInformation.dll
  runtimes\win\lib\netstandard1.1\System.Runtime.InteropServices.RuntimeInformation.dll=C:\Users\felix.b\.nuget\packages\system.runtime.interopservices.runtimeinformation\4.3.0\runtimes\win\lib\netstandard1.1\System.Runtime.InteropServices.RuntimeInformation.dll
  System.Runtime.Loader.dll=C:\Users\felix.b\.nuget\packages\system.runtime.loader\4.3.0\lib\netstandard1.5\System.Runtime.Loader.dll
  System.Runtime.Numerics.dll=C:\Users\felix.b\.nuget\packages\system.runtime.numerics\4.3.0\lib\netstandard1.3\System.Runtime.Numerics.dll
  runtimes\osx\lib\netstandard1.6\System.Security.Cryptography.Algorithms.dll=C:\Users\felix.b\.nuget\packages\system.security.cryptography.algorithms\4.3.0\runtimes\osx\lib\netstandard1.6\System.Security.Cryptography.Algorithms.dll
  runtimes\unix\lib\netstandard1.6\System.Security.Cryptography.Algorithms.dll=C:\Users\felix.b\.nuget\packages\system.security.cryptography.algorithms\4.3.0\runtimes\unix\lib\netstandard1.6\System.Security.Cryptography.Algorithms.dll
  runtimes\win\lib\netstandard1.6\System.Security.Cryptography.Algorithms.dll=C:\Users\felix.b\.nuget\packages\system.security.cryptography.algorithms\4.3.0\runtimes\win\lib\netstandard1.6\System.Security.Cryptography.Algorithms.dll
  runtimes\unix\lib\netstandard1.6\System.Security.Cryptography.Cng.dll=C:\Users\felix.b\.nuget\packages\system.security.cryptography.cng\4.3.0\runtimes\unix\lib\netstandard1.6\System.Security.Cryptography.Cng.dll
  runtimes\win\lib\netstandard1.6\System.Security.Cryptography.Cng.dll=C:\Users\felix.b\.nuget\packages\system.security.cryptography.cng\4.3.0\runtimes\win\lib\netstandard1.6\System.Security.Cryptography.Cng.dll
  runtimes\unix\lib\netstandard1.3\System.Security.Cryptography.Csp.dll=C:\Users\felix.b\.nuget\packages\system.security.cryptography.csp\4.3.0\runtimes\unix\lib\netstandard1.3\System.Security.Cryptography.Csp.dll
  runtimes\win\lib\netstandard1.3\System.Security.Cryptography.Csp.dll=C:\Users\felix.b\.nuget\packages\system.security.cryptography.csp\4.3.0\runtimes\win\lib\netstandard1.3\System.Security.Cryptography.Csp.dll
  runtimes\unix\lib\netstandard1.3\System.Security.Cryptography.Encoding.dll=C:\Users\felix.b\.nuget\packages\system.security.cryptography.encoding\4.3.0\runtimes\unix\lib\netstandard1.3\System.Security.Cryptography.Encoding.dll
  runtimes\win\lib\netstandard1.3\System.Security.Cryptography.Encoding.dll=C:\Users\felix.b\.nuget\packages\system.security.cryptography.encoding\4.3.0\runtimes\win\lib\netstandard1.3\System.Security.Cryptography.Encoding.dll
  System.Security.Cryptography.OpenSsl.dll=C:\Users\felix.b\.nuget\packages\system.security.cryptography.openssl\4.3.0\lib\netstandard1.6\System.Security.Cryptography.OpenSsl.dll
  runtimes\unix\lib\netstandard1.6\System.Security.Cryptography.OpenSsl.dll=C:\Users\felix.b\.nuget\packages\system.security.cryptography.openssl\4.3.0\runtimes\unix\lib\netstandard1.6\System.Security.Cryptography.OpenSsl.dll
  System.Security.Cryptography.Primitives.dll=C:\Users\felix.b\.nuget\packages\system.security.cryptography.primitives\4.3.0\lib\netstandard1.3\System.Security.Cryptography.Primitives.dll
  runtimes\unix\lib\netstandard1.6\System.Security.Cryptography.X509Certificates.dll=C:\Users\felix.b\.nuget\packages\system.security.cryptography.x509certificates\4.3.0\runtimes\unix\lib\netstandard1.6\System.Security.Cryptography.X509Certificates.dll
  runtimes\win\lib\netstandard1.6\System.Security.Cryptography.X509Certificates.dll=C:\Users\felix.b\.nuget\packages\system.security.cryptography.x509certificates\4.3.0\runtimes\win\lib\netstandard1.6\System.Security.Cryptography.X509Certificates.dll
  System.Text.RegularExpressions.dll=C:\Users\felix.b\.nuget\packages\system.text.regularexpressions\4.3.0\lib\netstandard1.6\System.Text.RegularExpressions.dll
  System.Threading.dll=C:\Users\felix.b\.nuget\packages\system.threading\4.3.0\lib\netstandard1.3\System.Threading.dll
  System.Threading.Tasks.Extensions.dll=C:\Users\felix.b\.nuget\packages\system.threading.tasks.extensions\4.3.0\lib\netstandard1.0\System.Threading.Tasks.Extensions.dll
  System.ValueTuple.dll=C:\Users\felix.b\.nuget\packages\system.valuetuple\4.3.0\lib\netstandard1.0\System.ValueTuple.dll
  System.Xml.ReaderWriter.dll=C:\Users\felix.b\.nuget\packages\system.xml.readerwriter\4.3.0\lib\netstandard1.3\System.Xml.ReaderWriter.dll
  System.Xml.XDocument.dll=C:\Users\felix.b\.nuget\packages\system.xml.xdocument\4.3.0\lib\netstandard1.3\System.Xml.XDocument.dll
  System.Xml.XmlDocument.dll=C:\Users\felix.b\.nuget\packages\system.xml.xmldocument\4.3.0\lib\netstandard1.3\System.Xml.XmlDocument.dll
  System.Xml.XmlSerializer.dll=C:\Users\felix.b\.nuget\packages\system.xml.xmlserializer\4.3.0\lib\netstandard1.3\System.Xml.XmlSerializer.dll
```
From here I easily build a dictionary of assembly file path by assembly name. In the ```AssemblyLoadContext.Resolving``` handler, given an assembly name, I just lookup its path and load it from there.

**Comment by felix-b** [comment]
#### Not the way I wanted

I've abandoned attempts to re-host ResolvePublishAssemblies in-process inside the CLI, as there is no clear line in available NuGet packages. 

Another intention of mine was to use Roslyn's MSBuildWorkspace to inspect SLN files and correctly determine location of module projects. I've abandoned that too, because it isn't yet available in NETStandard (https://github.com/dotnet/roslyn/issues/17974). 

#### For now

To determine location of module projects, I assume simple flat solution structure: 
- module projects use default assembly names (equal to .CSPROJ file name)
- all project folders are named after project files (but without the .CSPROJ extension)
- all project folders reside in the solution folder

To locate all dependency assemblies, I will generate .PROJ file and run MSBuild command as shown in provious comment. I will intercept standard output and parse assembly name/path pairs into a dictionary.

**Comment by felix-b** [comment]
# Factual implementation summary

This comment summarizes design and implementation details as of the end of work.

### CLI syntax: ```nwheels publish```

#### Purpose

Builds microservice working folder, which then includes all necessary files to run a microservice.

#### Syntax

```nwheels publish [/path/to/source/folder] [--out /path/to/publish/folder] [--env /path/to/environment.xml] [--no-cli] [--project-config name]``` 

Parameters:

- **```/path/to/source/folder```** - optional. Specifies source folder of microservice project, where both ```microservice.xml``` and ```.csproj``` files reside. The path can be relative to current directory. If not specified, the default is current directory. 

Options:

- **```--out /path/to/publish/folder```** - optional. Destination microservice working folder. The folder will be created if it doesn't exist. If the folder exists, existing files will be overwritten. The path can be relative to source folder. If not specified, the default is **```./bin/microservice.working```** relative to source folder.

- **```--env /path/to/environment.xml```** - optional. Path to environment XML file to copy to microservice working folder. The file can have any arbitrary name (e.g. ```env-qa1.xml```). The path can be relative to source folder. If not specified, the default is **```environment.xml```** in the source folder.

- **```--no-cli```** - when specified, the NWheels CLI assembly (nwheels.dll) will not be copied to the publish folder. This is useful for F5 debugging in Visual Studio, as an attempt to publish the CLI project at that moment will fail with "access denied" error. If not specified, the default is to publish the CLI.

- **```--project-config name```** - optional. Specifies project configuration name (e.g. Debug or Release) for ```dotnet publish```, when it compiles the projects. If not specified, the default is Release.

### CLI syntax: ```nwheels run```

#### Purpose

Runs microservice from publish or source folder. Optionally, performs publish from source folder as a preliminary step.

#### Syntax

```nwheels run [/path/to/microservice/folder] [--no-publish] [--project-config name]```

Parameters:

- **```/path/to/microservice/folder```** - optional. Specifies _microservice folder_. If not specified, the default is current directory. Depending on whether _microservice folder_ is source or publish, one of the following happens:
  - If _microservice folder_ is publish folder created earlier with ```nwheels publish```, the command runs a microservice instance. It uses ```microservice.xml``` and ```environment.xml``` in the _microservice folder_.
  - If _microservice folder_ is source project, one of the following happens:
    - if ```--no-publish``` is specified, the command runs microservice right from the source folder; no files are copied (more details below). This mode is for F5 debugging in Visual Studio.
    - if ```--no-publish``` is not specified, the command first internally performs ```nwheels publish``` to ```./bin/microservice.working``` under the source folder, using ```environment.xml``` in the source folder. Then it runs microservice instance from the newly published location.

Options:

- **```--no-publish```** - this mode is for F5 debugging in Visual Studio. When specified, the microservice runs right from projects binary folders; no files are copied. Modules and dependency assemblies are automatically located, and loaded from where they were compiled or restored. WARNING: limitations apply to solution structure, see below. This option can only be used when _microservice folder_ is source project.

- **```--project-config name```** - optional. Specifies project configuration name (e.g. Debug or Release) for ```dotnet publish```, when it compiles the projects. If not specified, the default is Debug. This option cannot be specified with ```--no-publish```, or when _microservice folder_ is publish folder.
