### ISSUE TITLE
Microservice as a console project in user solution

### ISSUE THREAD

**Issue by felix-b** [felix-b/NWheels#53]
### Background

In ASP.NET Core, in contrast to classic ASP.NET, the entry point is a regular `Program` class, just like in a console program. 

Such approach makes me feel good. No IIS/Express magic that calls into my `Global.asax`. I'm in control of my application:

```c#
public class Program
{
    public static void Main(string[] args)
    {
        //... I can put my code here...

        var host = new WebHostBuilder()
            .UseKestrel()
            .UseContentRoot(Directory.GetCurrentDirectory())
            .UseStartup<Startup>()
            .UseApplicationInsights()
            .Build();

        //... and here...

        host.Run();

        //... and here...
    }
}
```

I think that the same applies to NWheels microservices. 

### Problem

`nwheels run` in the CLI includes several kinds of magic in order to dynamically host a microservice, which is defined in an external XML file. A kind of model-first approach. Here are its pros and cons:  

- Pro: might be very useful for testing
- Con: requires XML programming (not a C#-only solution)
- Con: takes the feeling of control away from our users
- Con: requires a complex `nwheels run` command in the CLI, which I'm sure implies future maintenance
- Con: increases microservice startup time
- Pro: saves our users a few lines of code

Bottom line: not sure `nwheels run` is worth. 

### Solution

Learn from ASP.NET Core, and let microservice be a console application project. Its `Program` class may look like this:

```c#
public class Program
{
    public static void Main(string[] args)
    {
        MicroserviceHost host = new MicroserviceHostBuilder()
            .UsePlafrormMessaging()
            .UsePlafrormRest()
            .UseFrameworkDdd()
            .UseFrameworkUidl()
            .UseAutofacInjectionAdapter()
            .UseKestrelHttpEndpointAdapter()
            .UseAngularWebUIAdapter()
            .UseFeature<FirstFeature>()
            .UseFeature<SecondFeature>()
            .Build();

        host.Run();
    }
}
```

and the project file may look like this:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp1.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NWheels.Kernel" Version="1.0.0" />
    <PackageReference Include="NWheels.Kernel.Injection.Adapters.Autofac" Version="1.0.0" />
    <PackageReference Include="NWheels.Platform.Messaging" Version="1.0.0" />
    <PackageReference Include="NWheels.Platform.Messaging.Adapters.Kestrel" Version="1.0.0" />
    <PackageReference Include="NWheels.Platform.Rest" Version="1.0.0" />
    <PackageReference Include="NWheels.Framework.Ddd" Version="1.0.0" />
    <PackageReference Include="NWheels.Framework.Uidl" Version="1.0.0" />
    <PackageReference Include="NWheels.Framework.Uidl.Adapters.Angular" Version="1.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MySystem.FirstProject.csproj" />
    <ProjectReference Include="..\MySystem.SecondProject.csproj" />
  </ItemGroup>

</Project>
```

With project like this, all dependencies are resolved by .NET Core. No more magic. No XML. Everything is written in C#, plain clear and explicit.

### Implementation Details

Implementation can be pretty elegant:
- Fluent APIs of `MicroserviceHostBuilder` populate a `BootConfiguration` object
- No need to populate `AssemblyLocationMap` inside `BootConfiguration`.
- `MicroserviceHostBuilder.Build()` passes the populated `BootConfiguration` object to `MicroserviceHost`.
- `MicroserviceHost` implements a new method `Run()`, which reuses `LoadAndActivate` and `DeactivateAndUnload`.

### Backward Compatibility

The new approach naturally coexists with the existing functionality:
- `nwheels run` command in the CLI will continue to work as it does now.
- **MicroserviceHostBuilder** API will allow load a **microservice.xml** and an **environment.xml** file from specified path:
    ```c#
    MicroserviceHost host = new MicroserviceHostBuilder()
        .UseMicroserviceXml("/path/to/microservice.xml")
        .UseEnvironmentXml("/path/to/environment.xml")
        // additional UseXxxx APIs can be combined
        .Build();
    ```

### Multi-Tier Development Support

Multi-tier development of a microservice can be supported as follows:

- Tier 1 will:
    - extract all `UseXxxxx` calls on `MicroserviceHostBuilder` into a virtual method of a `LayerBuilder` class, which implements `IMicroserviceLayerBuilder`. 
- Tier 2 will:
    - create its own console application project for the microservice
    - reference Tier 1 microservice project through NuGet package
    - inherit the `LayerBuilder` class from Tier 1, and override the virtual method
    - in the overridden method, add `UseXxxxx` calls on `MicroserviceHostBuilder`

The same applies to all subsequent tiers. 

#### Tier 1

```c#
public class Program
{
    public static void Main(string[] args)
    {
        MicroserviceHost host = new MicroserviceHostBuilder()
            .UseLayer<LayerBuilder>()
            .Build();

        host.Run();
    }

    public class LayerBuilder : IMicroserviceLayerBuilder
    {
        public virtual void BuildLayer(MicroserviceHostBuilder hostBuilder)
        {
            hostBuilder
                .UsePlafrormMessaging()
                .UsePlafrormRest()
                .UseFrameworkDdd()
                .UseFrameworkUidl()
                .UseAutofacInjectionAdapter()
                .UseKestrelHttpEndpointAdapter()
                .UseAngularWebUIAdapter()
                .UseFeature<FirstFeature>()
                .UseFeature<SecondFeature>();
        }   
    }
}
```

#### Tier 2

Project file:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp1.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NWheels.Kernel" Version="1.0.0" />

    <!-- the following is reference to Tier 1 package -->
    <PackageReference Include="MySystem.MyMicroservice" Version="1.0.0" />
  </ItemGroup>

</Project>
```

Program.cs:
```c#
public class Program
{
    public static void Main(string[] args)
    {
        MicroserviceHost host = new MicroserviceHostBuilder()
            .UseLayer<Tier2LayerBuilder>()
            .Build();

        host.Run();
    }

    public class Tier2LayerBuilder : MySystem.MyMicroservice.Program.LayerBuilder
    {
        public override void BuildLayer(MicroserviceHostBuilder hostBuilder)
        {
            base.BuildLayer(hostBuilder);

            hostBuilder
                .UseFeature<ThirdFeature>()
                .UseFeature<FourthFeature>();
        }   
    }
}
```

**Comment by ILyaIL83** [comment]
It can be done for checking, but I have few doubts:
- Harder to configure. Instead of configuring one xml file, you have to configure proj file for references, cs file to enable new possibilities and rebuild project itself.
- Maintain and learn two ways of configuring, more complicated and less straightforward than one.

**Comment by felix-b** [comment]
Here is pros-and-cons summary:

- Pro: developers are in control of their application
- Pro: much simpler solution than the CLI run command
- Pro: no risk of future maintenance due to changes in .Net Core tooling
- Pro: C# based - full intellisense and validation by compiler
- Con: requires manually adding NWheels package references in .csproj files
- Con: increases learning curve - developers have to learn two ways of defining module stack, pros and cons of each, and it's an additional decision junction.

**Comment by felix-b** [comment]
Done in PR #81
